// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Which physical camera a session is bound to.
enum LensDirection {
  front,
  back,
}

/// Flash behavior for still capture. Auto and on are only meaningful on
/// lenses with a flash unit -- see [CameraCapabilityData.hasFlash].
enum FlashModeData {
  off,
  on,
  auto,
}

/// The subset of camera state changes the native side can independently
/// observe and must report asynchronously -- e.g. the OS reclaiming the
/// camera, or a permission revoked mid-session. The full controller state
/// machine, including states reachable only from Dart-initiated calls,
/// lives in CustomCameraController itself, not here.
enum NativeCameraEvent {
  disconnected,
  permissionRevoked,
  error,
}

/// Device-reported limits, read once at initialization time. The
/// governing rule: detect, never assume -- every field here is queried
/// from CameraCharacteristics/CameraInfo, never a hardcoded default,
/// since flash/zoom/focus/exposure support varies widely across Android
/// hardware.
class CameraCapabilityData {
  CameraCapabilityData({
    required this.hasFlash,
    required this.minZoomRatio,
    required this.maxZoomRatio,
    required this.supportsTapToFocus,
    required this.supportsExposureCompensation,
    required this.minExposureCompensation,
    required this.maxExposureCompensation,
    required this.availableLenses,
  });

  bool hasFlash;

  double minZoomRatio;

  double maxZoomRatio;

  bool supportsTapToFocus;

  bool supportsExposureCompensation;

  double minExposureCompensation;

  double maxExposureCompensation;

  List<LensDirection> availableLenses;

  List<Object?> _toList() {
    return <Object?>[
      hasFlash,
      minZoomRatio,
      maxZoomRatio,
      supportsTapToFocus,
      supportsExposureCompensation,
      minExposureCompensation,
      maxExposureCompensation,
      availableLenses,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraCapabilityData decode(Object result) {
    result as List<Object?>;
    return CameraCapabilityData(
      hasFlash: result[0]! as bool,
      minZoomRatio: result[1]! as double,
      maxZoomRatio: result[2]! as double,
      supportsTapToFocus: result[3]! as bool,
      supportsExposureCompensation: result[4]! as bool,
      minExposureCompensation: result[5]! as double,
      maxExposureCompensation: result[6]! as double,
      availableLenses: (result[7]! as List<Object?>).cast<LensDirection>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraCapabilityData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasFlash, other.hasFlash) && _deepEquals(minZoomRatio, other.minZoomRatio) && _deepEquals(maxZoomRatio, other.maxZoomRatio) && _deepEquals(supportsTapToFocus, other.supportsTapToFocus) && _deepEquals(supportsExposureCompensation, other.supportsExposureCompensation) && _deepEquals(minExposureCompensation, other.minExposureCompensation) && _deepEquals(maxExposureCompensation, other.maxExposureCompensation) && _deepEquals(availableLenses, other.availableLenses);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraCapabilityData(hasFlash: $hasFlash, minZoomRatio: $minZoomRatio, maxZoomRatio: $maxZoomRatio, supportsTapToFocus: $supportsTapToFocus, supportsExposureCompensation: $supportsExposureCompensation, minExposureCompensation: $minExposureCompensation, maxExposureCompensation: $maxExposureCompensation, availableLenses: $availableLenses)';
  }
}

/// Result of [CameraHostApi.initialize]: the detected capability plus the
/// Flutter texture id the bound preview is publishing to. Bundled into
/// one response because CameraX binds Preview as part of the same
/// bindToLifecycle() call that produces the capability-bearing CameraInfo
/// -- there is no separate "preview ready" moment to report.
class InitializeResult {
  InitializeResult({
    required this.capability,
    required this.textureId,
    required this.previewWidth,
    required this.previewHeight,
  });

  CameraCapabilityData capability;

  int textureId;

  /// The bound Preview use case's actual output resolution, in sensor
  /// (unrotated-for-display) pixels -- CustomCameraPreview needs this to
  /// compute cover/contain layout against the Texture's real aspect
  /// ratio rather than assuming one.
  int previewWidth;

  int previewHeight;

  List<Object?> _toList() {
    return <Object?>[
      capability,
      textureId,
      previewWidth,
      previewHeight,
    ];
  }

  Object encode() {
    return _toList();  }

  static InitializeResult decode(Object result) {
    result as List<Object?>;
    return InitializeResult(
      capability: result[0]! as CameraCapabilityData,
      textureId: result[1]! as int,
      previewWidth: result[2]! as int,
      previewHeight: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InitializeResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(capability, other.capability) && _deepEquals(textureId, other.textureId) && _deepEquals(previewWidth, other.previewWidth) && _deepEquals(previewHeight, other.previewHeight);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InitializeResult(capability: $capability, textureId: $textureId, previewWidth: $previewWidth, previewHeight: $previewHeight)';
  }
}

/// Result of [CameraHostApi.switchCamera]: mirrors [InitializeResult]
/// since switching cameras rebinds the whole CameraX use-case group,
/// including Preview -- the texture id (and possibly the preview
/// resolution) may change and capability must be re-read for the newly
/// bound lens.
class SwitchCameraResult {
  SwitchCameraResult({
    required this.capability,
    required this.textureId,
    required this.previewWidth,
    required this.previewHeight,
  });

  CameraCapabilityData capability;

  int textureId;

  int previewWidth;

  int previewHeight;

  List<Object?> _toList() {
    return <Object?>[
      capability,
      textureId,
      previewWidth,
      previewHeight,
    ];
  }

  Object encode() {
    return _toList();  }

  static SwitchCameraResult decode(Object result) {
    result as List<Object?>;
    return SwitchCameraResult(
      capability: result[0]! as CameraCapabilityData,
      textureId: result[1]! as int,
      previewWidth: result[2]! as int,
      previewHeight: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SwitchCameraResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(capability, other.capability) && _deepEquals(textureId, other.textureId) && _deepEquals(previewWidth, other.previewWidth) && _deepEquals(previewHeight, other.previewHeight);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SwitchCameraResult(capability: $capability, textureId: $textureId, previewWidth: $previewWidth, previewHeight: $previewHeight)';
  }
}

/// A point in normalized [0,1] preview-space, used for tap-to-focus and
/// tap-to-expose. Normalized rather than pixel-based so the Dart side
/// never needs to know the native preview surface's actual resolution --
/// consistent with the package's normalized-coordinate approach used
/// throughout (see the design doc's coordinate system architecture).
class NormalizedPointData {
  NormalizedPointData({
    required this.x,
    required this.y,
  });

  double x;

  double y;

  List<Object?> _toList() {
    return <Object?>[
      x,
      y,
    ];
  }

  Object encode() {
    return _toList();  }

  static NormalizedPointData decode(Object result) {
    result as List<Object?>;
    return NormalizedPointData(
      x: result[0]! as double,
      y: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NormalizedPointData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) && _deepEquals(y, other.y);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NormalizedPointData(x: $x, y: $y)';
  }
}

/// What a still-capture call produced.
class CaptureResultData {
  CaptureResultData({
    required this.filePath,
    required this.width,
    required this.height,
    required this.exifOrientationDegrees,
    required this.capturedLensDirection,
  });

  String filePath;

  int width;

  int height;

  int exifOrientationDegrees;

  LensDirection capturedLensDirection;

  List<Object?> _toList() {
    return <Object?>[
      filePath,
      width,
      height,
      exifOrientationDegrees,
      capturedLensDirection,
    ];
  }

  Object encode() {
    return _toList();  }

  static CaptureResultData decode(Object result) {
    result as List<Object?>;
    return CaptureResultData(
      filePath: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      exifOrientationDegrees: result[3]! as int,
      capturedLensDirection: result[4]! as LensDirection,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureResultData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(filePath, other.filePath) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(exifOrientationDegrees, other.exifOrientationDegrees) && _deepEquals(capturedLensDirection, other.capturedLensDirection);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureResultData(filePath: $filePath, width: $width, height: $height, exifOrientationDegrees: $exifOrientationDegrees, capturedLensDirection: $capturedLensDirection)';
  }
}

class CameraErrorData {
  CameraErrorData({
    required this.code,
    required this.message,
  });

  /// A stable code Dart maps onto its own typed exception hierarchy --
  /// not a free-text message on its own, so callers can branch on the
  /// failure kind rather than pattern-matching on message strings.
  String code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraErrorData decode(Object result) {
    result as List<Object?>;
    return CameraErrorData(
      code: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraErrorData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraErrorData(code: $code, message: $message)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LensDirection) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is FlashModeData) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is NativeCameraEvent) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is CameraCapabilityData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is InitializeResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is SwitchCameraResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is NormalizedPointData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is CaptureResultData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is CameraErrorData) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : LensDirection.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : FlashModeData.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCameraEvent.values[value];
      case 132:
        return CameraCapabilityData.decode(readValue(buffer)!);
      case 133:
        return InitializeResult.decode(readValue(buffer)!);
      case 134:
        return SwitchCameraResult.decode(readValue(buffer)!);
      case 135:
        return NormalizedPointData.decode(readValue(buffer)!);
      case 136:
        return CaptureResultData.decode(readValue(buffer)!);
      case 137:
        return CameraErrorData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> Kotlin. Commands the Dart controller issues to the native
/// camera session.
class CameraHostApi {
  /// Constructor for [CameraHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CameraHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Binds a CameraX session -- Preview and ImageCapture use cases -- to
  /// the plugin's own lifecycle owner (not an Activity's) and returns the
  /// detected device capability plus the texture id the preview is
  /// publishing to. Throws (via a FlutterError on the generated Dart
  /// side) if the requested lens direction is unavailable or the camera
  /// permission is not granted.
  Future<InitializeResult> initialize(LensDirection initialLensDirection) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[initialLensDirection]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as InitializeResult;
  }

  /// Unbinds the CameraX session and releases the camera. Safe to call
  /// from any state; calling it twice is a no-op, not an error.
  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Captures a still image at full resolution and writes it to a
  /// package-owned cache file. Throws if called while no session is
  /// bound.
  Future<CaptureResultData> captureImage() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.captureImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CaptureResultData;
  }

  /// Sets flash behavior for subsequent captures. Throws a FlutterError
  /// if the active lens has no flash unit -- callers should check
  /// [CameraCapabilityData.hasFlash] first, this is a defensive backstop.
  Future<void> setFlashMode(FlashModeData mode) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.setFlashMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Unbinds the current session and rebinds for the opposite lens
  /// direction, returning the newly bound capability and texture id (both
  /// may differ from the previous lens).
  Future<SwitchCameraResult> switchCamera(LensDirection lensDirection) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.switchCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[lensDirection]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as SwitchCameraResult;
  }

  /// Sets the zoom ratio. The native side clamps to the device's actual
  /// range as a defensive backstop -- see
  /// CameraCapability.clampZoom, which the Dart controller already
  /// applies before this is ever called.
  Future<void> setZoom(double zoomRatio) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.setZoom$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[zoomRatio]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Triggers autofocus AND auto-exposure metering together at a
  /// normalized preview point (the standard "tap to focus" gesture), or
  /// resumes continuous autofocus/default metering if [point] is null.
  ///
  /// Deliberately one call, not two -- CameraX's startFocusAndMetering()
  /// cancels an in-flight call when a second one starts on the same
  /// camera, so issuing separate AF and AE calls for the same tap is a
  /// guaranteed race, not just a theoretical one.
  Future<void> setMeteringPoint(NormalizedPointData? point) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.setMeteringPoint$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[point]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sets exposure compensation, in EV. The native side clamps to the
  /// device's actual range as a defensive backstop, mirroring [setZoom].
  Future<void> setExposureCompensation(double ev) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.setExposureCompensation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[ev]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Kotlin -> Dart. Async, natively-initiated notifications the controller
/// cannot poll for -- e.g. the camera permission being revoked at the OS
/// level while a session is active.
abstract class CameraFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onCameraEvent(NativeCameraEvent event, CameraErrorData? error);

  static void setUp(CameraFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.d3_camera.CameraFlutterApi.onCameraEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeCameraEvent arg_event = args[0]! as NativeCameraEvent;
          final CameraErrorData? arg_error = args[1] as CameraErrorData?;
          try {
            api.onCameraEvent(arg_event, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
