// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Which physical camera a session is bound to.
enum LensDirection {
  front,
  back,
}

/// The subset of camera state changes the native side can independently
/// observe and must report asynchronously -- e.g. the OS reclaiming the
/// camera, or a permission revoked mid-session. The full controller state
/// machine, including states reachable only from Dart-initiated calls,
/// lives in CustomCameraController itself, not here.
enum NativeCameraEvent {
  disconnected,
  permissionRevoked,
  error,
}

/// Device-reported limits, read once at initialization time. The
/// governing rule: detect, never assume -- every field here is queried
/// from CameraCharacteristics/CameraInfo, never a hardcoded default,
/// since flash/zoom/focus/exposure support varies widely across Android
/// hardware.
class CameraCapabilityData {
  CameraCapabilityData({
    required this.hasFlash,
    required this.minZoomRatio,
    required this.maxZoomRatio,
    required this.supportsTapToFocus,
    required this.supportsExposureCompensation,
    required this.minExposureCompensation,
    required this.maxExposureCompensation,
    required this.availableLenses,
  });

  bool hasFlash;

  double minZoomRatio;

  double maxZoomRatio;

  bool supportsTapToFocus;

  bool supportsExposureCompensation;

  double minExposureCompensation;

  double maxExposureCompensation;

  List<LensDirection> availableLenses;

  List<Object?> _toList() {
    return <Object?>[
      hasFlash,
      minZoomRatio,
      maxZoomRatio,
      supportsTapToFocus,
      supportsExposureCompensation,
      minExposureCompensation,
      maxExposureCompensation,
      availableLenses,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraCapabilityData decode(Object result) {
    result as List<Object?>;
    return CameraCapabilityData(
      hasFlash: result[0]! as bool,
      minZoomRatio: result[1]! as double,
      maxZoomRatio: result[2]! as double,
      supportsTapToFocus: result[3]! as bool,
      supportsExposureCompensation: result[4]! as bool,
      minExposureCompensation: result[5]! as double,
      maxExposureCompensation: result[6]! as double,
      availableLenses: (result[7]! as List<Object?>).cast<LensDirection>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraCapabilityData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasFlash, other.hasFlash) && _deepEquals(minZoomRatio, other.minZoomRatio) && _deepEquals(maxZoomRatio, other.maxZoomRatio) && _deepEquals(supportsTapToFocus, other.supportsTapToFocus) && _deepEquals(supportsExposureCompensation, other.supportsExposureCompensation) && _deepEquals(minExposureCompensation, other.minExposureCompensation) && _deepEquals(maxExposureCompensation, other.maxExposureCompensation) && _deepEquals(availableLenses, other.availableLenses);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraCapabilityData(hasFlash: $hasFlash, minZoomRatio: $minZoomRatio, maxZoomRatio: $maxZoomRatio, supportsTapToFocus: $supportsTapToFocus, supportsExposureCompensation: $supportsExposureCompensation, minExposureCompensation: $minExposureCompensation, maxExposureCompensation: $maxExposureCompensation, availableLenses: $availableLenses)';
  }
}

class CameraErrorData {
  CameraErrorData({
    required this.code,
    required this.message,
  });

  /// A stable code Dart maps onto its own typed exception hierarchy --
  /// not a free-text message on its own, so callers can branch on the
  /// failure kind rather than pattern-matching on message strings.
  String code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraErrorData decode(Object result) {
    result as List<Object?>;
    return CameraErrorData(
      code: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraErrorData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraErrorData(code: $code, message: $message)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LensDirection) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NativeCameraEvent) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is CameraCapabilityData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CameraErrorData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : LensDirection.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCameraEvent.values[value];
      case 131:
        return CameraCapabilityData.decode(readValue(buffer)!);
      case 132:
        return CameraErrorData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> Kotlin. Commands the Dart controller issues to the native
/// camera session.
class CameraHostApi {
  /// Constructor for [CameraHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CameraHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Binds a CameraX session to the plugin's own lifecycle owner (not an
  /// Activity's) and returns the detected device capability. Throws (via
  /// a FlutterError on the generated Dart side) if the requested lens
  /// direction is unavailable or the camera permission is not granted.
  Future<CameraCapabilityData> initialize(LensDirection initialLensDirection) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[initialLensDirection]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CameraCapabilityData;
  }

  /// Unbinds the CameraX session and releases the camera. Safe to call
  /// from any state; calling it twice is a no-op, not an error.
  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.d3_camera.CameraHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Kotlin -> Dart. Async, natively-initiated notifications the controller
/// cannot poll for -- e.g. the camera permission being revoked at the OS
/// level while a session is active.
abstract class CameraFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onCameraEvent(NativeCameraEvent event, CameraErrorData? error);

  static void setUp(CameraFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.d3_camera.CameraFlutterApi.onCameraEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeCameraEvent arg_event = args[0]! as NativeCameraEvent;
          final CameraErrorData? arg_error = args[1] as CameraErrorData?;
          try {
            api.onCameraEvent(arg_event, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
