// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.d3.d3_camera

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object CameraApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Which physical camera a session is bound to. */
enum class LensDirection(val raw: Int) {
  FRONT(0),
  BACK(1);

  companion object {
    fun ofRaw(raw: Int): LensDirection? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Flash behavior for still capture. Auto and on are only meaningful on
 * lenses with a flash unit -- see [CameraCapabilityData.hasFlash].
 */
enum class FlashModeData(val raw: Int) {
  OFF(0),
  ON(1),
  AUTO(2);

  companion object {
    fun ofRaw(raw: Int): FlashModeData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The subset of camera state changes the native side can independently
 * observe and must report asynchronously -- e.g. the OS reclaiming the
 * camera, or a permission revoked mid-session. The full controller state
 * machine, including states reachable only from Dart-initiated calls,
 * lives in CustomCameraController itself, not here.
 */
enum class NativeCameraEvent(val raw: Int) {
  DISCONNECTED(0),
  PERMISSION_REVOKED(1),
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): NativeCameraEvent? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Device-reported limits, read once at initialization time. The
 * governing rule: detect, never assume -- every field here is queried
 * from CameraCharacteristics/CameraInfo, never a hardcoded default,
 * since flash/zoom/focus/exposure support varies widely across Android
 * hardware.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CameraCapabilityData (
  val hasFlash: Boolean,
  val minZoomRatio: Double,
  val maxZoomRatio: Double,
  val supportsTapToFocus: Boolean,
  val supportsExposureCompensation: Boolean,
  val minExposureCompensation: Double,
  val maxExposureCompensation: Double,
  val availableLenses: List<LensDirection>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraCapabilityData {
      val hasFlash = pigeonVar_list[0] as Boolean
      val minZoomRatio = pigeonVar_list[1] as Double
      val maxZoomRatio = pigeonVar_list[2] as Double
      val supportsTapToFocus = pigeonVar_list[3] as Boolean
      val supportsExposureCompensation = pigeonVar_list[4] as Boolean
      val minExposureCompensation = pigeonVar_list[5] as Double
      val maxExposureCompensation = pigeonVar_list[6] as Double
      val availableLenses = pigeonVar_list[7] as List<LensDirection>
      return CameraCapabilityData(hasFlash, minZoomRatio, maxZoomRatio, supportsTapToFocus, supportsExposureCompensation, minExposureCompensation, maxExposureCompensation, availableLenses)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hasFlash,
      minZoomRatio,
      maxZoomRatio,
      supportsTapToFocus,
      supportsExposureCompensation,
      minExposureCompensation,
      maxExposureCompensation,
      availableLenses,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CameraCapabilityData
    return CameraApiPigeonUtils.deepEquals(this.hasFlash, other.hasFlash) && CameraApiPigeonUtils.deepEquals(this.minZoomRatio, other.minZoomRatio) && CameraApiPigeonUtils.deepEquals(this.maxZoomRatio, other.maxZoomRatio) && CameraApiPigeonUtils.deepEquals(this.supportsTapToFocus, other.supportsTapToFocus) && CameraApiPigeonUtils.deepEquals(this.supportsExposureCompensation, other.supportsExposureCompensation) && CameraApiPigeonUtils.deepEquals(this.minExposureCompensation, other.minExposureCompensation) && CameraApiPigeonUtils.deepEquals(this.maxExposureCompensation, other.maxExposureCompensation) && CameraApiPigeonUtils.deepEquals(this.availableLenses, other.availableLenses)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.hasFlash)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.minZoomRatio)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.maxZoomRatio)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.supportsTapToFocus)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.supportsExposureCompensation)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.minExposureCompensation)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.maxExposureCompensation)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.availableLenses)
    return result
  }
  override fun toString(): String {
    return "CameraCapabilityData(hasFlash=$hasFlash, minZoomRatio=$minZoomRatio, maxZoomRatio=$maxZoomRatio, supportsTapToFocus=$supportsTapToFocus, supportsExposureCompensation=$supportsExposureCompensation, minExposureCompensation=$minExposureCompensation, maxExposureCompensation=$maxExposureCompensation, availableLenses=$availableLenses)"
  }
}

/**
 * Result of [CameraHostApi.initialize]: the detected capability plus the
 * Flutter texture id the bound preview is publishing to. Bundled into
 * one response because CameraX binds Preview as part of the same
 * bindToLifecycle() call that produces the capability-bearing CameraInfo
 * -- there is no separate "preview ready" moment to report.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitializeResult (
  val capability: CameraCapabilityData,
  val textureId: Long,
  /**
   * The bound Preview use case's actual output resolution, in sensor
   * (unrotated-for-display) pixels -- CustomCameraPreview needs this to
   * compute cover/contain layout against the Texture's real aspect
   * ratio rather than assuming one.
   */
  val previewWidth: Long,
  val previewHeight: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializeResult {
      val capability = pigeonVar_list[0] as CameraCapabilityData
      val textureId = pigeonVar_list[1] as Long
      val previewWidth = pigeonVar_list[2] as Long
      val previewHeight = pigeonVar_list[3] as Long
      return InitializeResult(capability, textureId, previewWidth, previewHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      capability,
      textureId,
      previewWidth,
      previewHeight,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InitializeResult
    return CameraApiPigeonUtils.deepEquals(this.capability, other.capability) && CameraApiPigeonUtils.deepEquals(this.textureId, other.textureId) && CameraApiPigeonUtils.deepEquals(this.previewWidth, other.previewWidth) && CameraApiPigeonUtils.deepEquals(this.previewHeight, other.previewHeight)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.capability)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.textureId)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.previewWidth)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.previewHeight)
    return result
  }
  override fun toString(): String {
    return "InitializeResult(capability=$capability, textureId=$textureId, previewWidth=$previewWidth, previewHeight=$previewHeight)"
  }
}

/**
 * Result of [CameraHostApi.switchCamera]: mirrors [InitializeResult]
 * since switching cameras rebinds the whole CameraX use-case group,
 * including Preview -- the texture id (and possibly the preview
 * resolution) may change and capability must be re-read for the newly
 * bound lens.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SwitchCameraResult (
  val capability: CameraCapabilityData,
  val textureId: Long,
  val previewWidth: Long,
  val previewHeight: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SwitchCameraResult {
      val capability = pigeonVar_list[0] as CameraCapabilityData
      val textureId = pigeonVar_list[1] as Long
      val previewWidth = pigeonVar_list[2] as Long
      val previewHeight = pigeonVar_list[3] as Long
      return SwitchCameraResult(capability, textureId, previewWidth, previewHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      capability,
      textureId,
      previewWidth,
      previewHeight,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SwitchCameraResult
    return CameraApiPigeonUtils.deepEquals(this.capability, other.capability) && CameraApiPigeonUtils.deepEquals(this.textureId, other.textureId) && CameraApiPigeonUtils.deepEquals(this.previewWidth, other.previewWidth) && CameraApiPigeonUtils.deepEquals(this.previewHeight, other.previewHeight)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.capability)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.textureId)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.previewWidth)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.previewHeight)
    return result
  }
  override fun toString(): String {
    return "SwitchCameraResult(capability=$capability, textureId=$textureId, previewWidth=$previewWidth, previewHeight=$previewHeight)"
  }
}

/**
 * A point in normalized [0,1] preview-space, used for tap-to-focus and
 * tap-to-expose. Normalized rather than pixel-based so the Dart side
 * never needs to know the native preview surface's actual resolution --
 * consistent with the package's normalized-coordinate approach used
 * throughout (see the design doc's coordinate system architecture).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NormalizedPointData (
  val x: Double,
  val y: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NormalizedPointData {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      return NormalizedPointData(x, y)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NormalizedPointData
    return CameraApiPigeonUtils.deepEquals(this.x, other.x) && CameraApiPigeonUtils.deepEquals(this.y, other.y)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.x)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.y)
    return result
  }
  override fun toString(): String {
    return "NormalizedPointData(x=$x, y=$y)"
  }
}

/**
 * What a still-capture call produced.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CaptureResultData (
  val filePath: String,
  val width: Long,
  val height: Long,
  val exifOrientationDegrees: Long,
  val capturedLensDirection: LensDirection
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureResultData {
      val filePath = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val exifOrientationDegrees = pigeonVar_list[3] as Long
      val capturedLensDirection = pigeonVar_list[4] as LensDirection
      return CaptureResultData(filePath, width, height, exifOrientationDegrees, capturedLensDirection)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      filePath,
      width,
      height,
      exifOrientationDegrees,
      capturedLensDirection,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CaptureResultData
    return CameraApiPigeonUtils.deepEquals(this.filePath, other.filePath) && CameraApiPigeonUtils.deepEquals(this.width, other.width) && CameraApiPigeonUtils.deepEquals(this.height, other.height) && CameraApiPigeonUtils.deepEquals(this.exifOrientationDegrees, other.exifOrientationDegrees) && CameraApiPigeonUtils.deepEquals(this.capturedLensDirection, other.capturedLensDirection)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.filePath)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.width)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.height)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.exifOrientationDegrees)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.capturedLensDirection)
    return result
  }
  override fun toString(): String {
    return "CaptureResultData(filePath=$filePath, width=$width, height=$height, exifOrientationDegrees=$exifOrientationDegrees, capturedLensDirection=$capturedLensDirection)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraErrorData (
  /**
   * A stable code Dart maps onto its own typed exception hierarchy --
   * not a free-text message on its own, so callers can branch on the
   * failure kind rather than pattern-matching on message strings.
   */
  val code: String,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraErrorData {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return CameraErrorData(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CameraErrorData
    return CameraApiPigeonUtils.deepEquals(this.code, other.code) && CameraApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.code)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "CameraErrorData(code=$code, message=$message)"
  }
}
private open class CameraApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LensDirection.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FlashModeData.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeCameraEvent.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraCapabilityData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializeResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SwitchCameraResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NormalizedPointData.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureResultData.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraErrorData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LensDirection -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is FlashModeData -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NativeCameraEvent -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is CameraCapabilityData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is InitializeResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SwitchCameraResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NormalizedPointData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CaptureResultData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CameraErrorData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart -> Kotlin. Commands the Dart controller issues to the native
 * camera session.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CameraHostApi {
  /**
   * Binds a CameraX session -- Preview and ImageCapture use cases -- to
   * the plugin's own lifecycle owner (not an Activity's) and returns the
   * detected device capability plus the texture id the preview is
   * publishing to. Throws (via a FlutterError on the generated Dart
   * side) if the requested lens direction is unavailable or the camera
   * permission is not granted.
   */
  suspend fun initialize(initialLensDirection: LensDirection): InitializeResult
  /**
   * Unbinds the CameraX session and releases the camera. Safe to call
   * from any state; calling it twice is a no-op, not an error.
   */
  suspend fun dispose()
  /**
   * Captures a still image at full resolution and writes it to a
   * package-owned cache file. Throws if called while no session is
   * bound.
   */
  suspend fun captureImage(): CaptureResultData
  /**
   * Sets flash behavior for subsequent captures. Throws a FlutterError
   * if the active lens has no flash unit -- callers should check
   * [CameraCapabilityData.hasFlash] first, this is a defensive backstop.
   */
  suspend fun setFlashMode(mode: FlashModeData)
  /**
   * Unbinds the current session and rebinds for the opposite lens
   * direction, returning the newly bound capability and texture id (both
   * may differ from the previous lens).
   */
  suspend fun switchCamera(lensDirection: LensDirection): SwitchCameraResult
  /**
   * Sets the zoom ratio. The native side clamps to the device's actual
   * range as a defensive backstop -- see
   * CameraCapability.clampZoom, which the Dart controller already
   * applies before this is ever called.
   */
  suspend fun setZoom(zoomRatio: Double)
  /**
   * Triggers autofocus AND auto-exposure metering together at a
   * normalized preview point (the standard "tap to focus" gesture), or
   * resumes continuous autofocus/default metering if [point] is null.
   *
   * Deliberately one call, not two -- CameraX's startFocusAndMetering()
   * cancels an in-flight call when a second one starts on the same
   * camera, so issuing separate AF and AE calls for the same tap is a
   * guaranteed race, not just a theoretical one.
   */
  suspend fun setMeteringPoint(point: NormalizedPointData?)
  /**
   * Sets exposure compensation, in EV. The native side clamps to the
   * device's actual range as a defensive backstop, mirroring [setZoom].
   */
  suspend fun setExposureCompensation(ev: Double)

  companion object {
    /** The codec used by CameraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CameraApiPigeonCodec()
    }
    /** Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val initialLensDirectionArg = args[0] as LensDirection
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.initialize(initialLensDirectionArg))
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.dispose()
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.captureImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.captureImage())
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.setFlashMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as FlashModeData
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setFlashMode(modeArg)
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.switchCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val lensDirectionArg = args[0] as LensDirection
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.switchCamera(lensDirectionArg))
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.setZoom$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val zoomRatioArg = args[0] as Double
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setZoom(zoomRatioArg)
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.setMeteringPoint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pointArg = args[0] as NormalizedPointData?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setMeteringPoint(pointArg)
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.d3_camera.CameraHostApi.setExposureCompensation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val evArg = args[0] as Double
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setExposureCompensation(evArg)
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Kotlin -> Dart. Async, natively-initiated notifications the controller
 * cannot poll for -- e.g. the camera permission being revoked at the OS
 * level while a session is active.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class CameraFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CameraFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CameraApiPigeonCodec()
    }
  }
  suspend fun onCameraEvent(eventArg: NativeCameraEvent, errorArg: CameraErrorData?)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.d3_camera.CameraFlutterApi.onCameraEvent$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg, errorArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CameraApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
